### ISSUE TITLE
Bonus Episode Aug 7th - Vote or Suggest

### ISSUE THREAD

**Issue by heitorlessa** [aws-samples/aws-serverless-airline-booking#1]
Hey everyone,

Please **react** to comments with 👍 or add a new suggestion as a comment.

**Have the following in mind before suggesting new topics**

* Is it doable to implement, discuss and troubleshoot within 60 minutes?
* Have you double checked [episode descriptions](https://pages.awscloud.com/GLOBAL-devstrategy-OE-BuildOnServerless-2019-reg-event.html) to avoid duplication?

**Comment by Folinus** [comment]
Hello Heitor,

I would love an episode on serverless best practices for batch processing, especially when building the frontend and services with AWS Amplify. For example, an airline booking system might have an hourly CRON job that updates inventory from external APIs. How would you recommend implementing those with the current architecture? Would you spin up additional services like AWS Glue, AWS Batch, etc? How do those interact with the services configured by Amplify?

Thanks,
Kevin

**Comment by barrybrianbarrios** [comment]
Can you demonstrate how to convert this web app to a smartphone app? How much more work is required to convert it to a smartphone app and how will it look like using an iphone and an android phone? Is there a emulator in AWS to test on different mobile devices similar to android: https://developer.android.com/studio/run/emulator

It'll be great if you can show step functions for one of the services.

**Comment by heitorlessa** [comment]
> Hello Heitor,
> 
> I would love an episode on serverless best practices for batch processing, especially when building the frontend and services with AWS Amplify. For example, an airline booking system might have an hourly CRON job that updates inventory from external APIs. How would you recommend implementing those with the current architecture? Would you spin up additional services like AWS Glue, AWS Batch, etc? How do those interact with the services configured by Amplify?
> 
> Thanks,
> Kevin

That could likely be our bonus episode depending on how many votes we get by July \ o /.

There's quite a few ways to do it, and all you'd need to interact with would be to have permissions to make a call to the Catalog service -- At this stage, a valid JWT Token that could make a POST using createFlight/updateFlight, which we could [restrict to a group](https://aws-amplify.github.io/docs/cli/graphql#auth) called "Admin/Operators/ETL". 

I'd normally favour looking up for an authority in this space where flights are up-to-date, if there's no open data, I'd create a fake daily batch using `faker`, and create an ETL process using Step Functions to have more control over Try/Backoff, etc. AWS Batch and AWS Glue could very well work here too - Specially Glue where you could have a Crawler for flight changes, which ultimately updates existing Bookings and those searching for Flights via GraphQL Subscriptions too :)

**Comment by dancomanlive** [comment]
The general approach towards noSql data modelling is to design the queries first and then derive the structure of the database from the queries. With AppSync GraphQL the structure of the database is  based on the schema. Would be great to learn how to best create a schema based on access patterns ( the types of queries to be supported).

**Comment by heitorlessa** [comment]
> The general approach towards noSql data modelling is to design the queries first and then derive the structure of the database from the queries. With AppSync GraphQL the structure of the database is based on the schema. Would be great to learn how to best create a schema based on access patterns ( the types of queries to be supported).

What if we do a bonus episode solely focused on working with a Single Table?

That way, we would recreate the same schema that uses multiple access patterns, resolvers from scratch and without `@model` directive from Amplify CLI. 

Would that work? If so, that's up for voting ;)

**Comment by bhavintandel** [comment]
can we do some various methods to do the stress-test or load-test for this serverless application? Also if we could calculate the time for requests when we have many parallel updates. Just so that we have a benchmark for our application and be sure that our app will be fine during heavy load.

**Comment by barrybrianbarrios** [comment]
> Can you demonstrate how to convert this web app to a smartphone app? How much more work is required to convert it to a smartphone app and how will it look like using an iphone and an android phone? Is there a emulator in AWS to test on different mobile devices similar to android: https://developer.android.com/studio/run/emulator
> I see you are using Quasar. I'm curious if it's very easy to convert a web app to a mobile app. Can you demonstrate how to use Apache Cordova for a webapp.
> 
> It'll be great if you can show step functions for one of the services. Also can you perform A/B testing on different versions of your web app using lambda@edge, and how to set it up where some of the users see one version of the website and another set of users see another version of the website. And how to use look to book ratio or conversion rates as a metric to determine which webpage to use in future releases and perform more A/B testing or multi-armed bandits? the demand for bookings can be determined using a simulation as a way to test the website to mimic reality. Is that hard to do?

or if it's too much to do then never mind. What about a streaming app using dynamodb streams simulating booking traffic to the website  similar to what bhavintandel  to stress test the serverless application. It can be intergrated with kinesis streams. Basically simulate the booking traffic with some historical data and see how the application handles the load. This can be done using a combination of lambda, dynamodb streams and kinensis: 
Create a kinesis stream and use it to trigger a lambda function and 
create a dynamodb table to insert the bookings and enable dynamodb streams
For example, once a booking is made, that booking data is added to a DynamoDB table. 
This event invokes another application that sends a welcome email to the new customer that
shows a confirmation number of the booking made. And we can also add the
functionality of cancellations and keeping the inventory open. This will be to determine if inventory is available. The application will determine available inventory and also the application needs to make sure that if two customers book the same flight at the same time that only one gets the flight, it has to handle racing conditions. Is this something that can be doable in an episode? Let me know your thoughts.

**Comment by flochaz** [comment]
I would be really interested to see how to run all that locally for quick and offline development cycle. Especially for Step functions and other integration.

**Comment by PetarGK** [comment]
It will be good idea to see this project in production ready fashion. What I mean here is using separate AWS accounts for every one env., apply appropriate IAM policies, implement CI/CD using AWS CDK, demonstrate development/deployment process.

**Comment by heitorlessa** [comment]
> can we do some various methods to do the stress-test or load-test for this serverless application? Also if we could calculate the time for requests when we have many parallel updates. Just so that we have a benchmark for our application and be sure that our app will be fine during heavy load.

We're going with your idea -- I've heard the same feedback over and over across AWS events and Meetup, so on Aug 7th will be about Performance Load Testing and improving the overall app based on its results --- So Thank you!!

Thanks to everyone for their inputs, and I'm adding them into #30
