### ISSUE TITLE
#current-cloud-backend is gitignored but used in amplify.yml

### ISSUE THREAD

**Issue by praghavan039** [aws-samples/aws-serverless-airline-booking#104]
Hi,

I see below line in amplify.yml

`- export STACK_NAME=$(jq -r '.providers.awscloudformation.StackName' ./amplify/#current-cloud-backend/amplify-meta.json)`

But, #current-cloud-backend is added in .gitignore. When I try to build, I get this error.

> 2020-03-16T21:09:26.480Z [WARNING]: jq: error: Could not open file ./amplify/#current-cloud-backend/amplify-meta.json: No such file or directory
> 2020-03-16T21:09:26.481Z [INFO]: # Executing command: export STACK_NAME=
> 

Also, I've one other issue with Access Denied warning. What's the reason for this message.

> 020-03-16T21:09:19.848Z [INFO]: Note: It is recommended to run this command from the root of your app directory
> 2020-03-16T21:09:24.862Z [WARNING]: - Initializing your environment: develop
> 2020-03-16T21:09:24.952Z [WARNING]: (node:1200) UnhandledPromiseRejectionWarning: AccessDenied: Access Denied
>                                     at Request.extractError (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/services/s3.js:816:35)
>                                     at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
>                                     at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
>                                     at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
>                                     at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
>                                     at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
>                                     at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
>                                     at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
>                                     at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
>                                     at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
> 2020-03-16T21:09:24.953Z [WARNING]: (node:1200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
>                                     (node:1200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by heitorlessa** [comment]
Hey - Thanks for reaching out. Is that error within Amplify Console build
logs?

That reads as if the first command “amplifyPush —simple” didn’t run — If
you could share in a fist the full logs I’d be happy to take a look at it.

The reason why that’s in gitignore it’s because amplify.yml runs at CI
(Amplify Console). Amplify creates that folder during either: project
initialisation for the first time or syncing an existing deployment

**Comment by praghavan039** [comment]
Thanks for the comments. There was some issue in the configuration/environment setup. On resetup, it worked.

**Comment by heitorlessa** [comment]
Glad it worked out :)
