### ISSUE TITLE
[Booking] Switch from Step Functions Standard Workflow to Step Functions Express Workflow

### ISSUE THREAD

**Issue by SimonEismann** [aws-samples/aws-serverless-airline-booking#116]
Currently, Step Functions seems to make up a large portion of the costs of this project. When putting the airline under some load, the Step Functions were responsible for ~55$ out of the total costs of ~67$.

When switching to Express Workflows, the cost incurred by Step Functions for the same workload was reduced to ~0.5$.

Currently, the state machine consists of about 10 transitions, which at 0.000025$ per transition comes down to 0.000250$ per execution. 

The express workflow uses 64 MB for ~1000 ms per execution, so it requires ~0.0625 GB-s of billed memory. At 0.00001667$/GB-s this comes to costs of about 0.000001$ per request, so a ~95% cost decrease. 

Is there any functional reason to stick to a Standard Workflows? Maybe some consistency guarantees or something?

**Comment by heitorlessa** [comment]
Hey @SimonEismann - Primarily two reasons:

1) Express workflows weren't available when I started this example
2) Standard workflows have a visual debugging that is helpful when demonstrating how Saga pattern could work in Serverless

There's a potential third that Express workflows run at least once, and we'd need to ensure idempotent actions which is good outcome either way. 

I'd be happy to have a Parameter to toggle the use of Standard vs Express from a cost optimization perspective. From a business perspective it's not immediately relevant given the amount of transitions, visual debugger, and not needing high throughput.
