### ISSUE TITLE
Documentation update Request

### ISSUE THREAD

**Issue by medvedevden1s** [aws-samples/aws-serverless-airline-booking#127]
I see that in getting started we have next info: **NOTICE**: AWS AppSync is not part of [Free tier] but it's not true

AppSync  has a  Free Tier
The Free Tier offers the following monthly usage levels at no charge for 12 months after you sign up for an AWS account.
250,000 query or data modification operations
250,000 real-time updates
600,000 connection-minutes
Use beyond these levels is billed at the published rates. The AWS AppSync Free Tier automatically expires after 12 months.

https://aws.amazon.com/appsync/pricing/

**Comment by heitorlessa** [comment]
Thanks for creating the issue @medvedevden1s much appreciated :) I've just updated that doc - AppSync wasn't part of the Free Tier back then.
