### ISSUE TITLE
Performance testing stack returning `No rule to make target `deploy`' error

### ISSUE THREAD

**Issue by pputhran** [aws-samples/aws-serverless-airline-booking#131]
On deploying the Perf stack, I am getting the error - `No rule to make target deploy`

<img width="1041" alt="Screen Shot 2020-09-26 at 10 33 10 AM" src="https://user-images.githubusercontent.com/6620128/94337677-4e545f00-ffe4-11ea-8fae-01263a18be55.png">

The [MakeFile](https://github.com/aws-samples/aws-serverless-airline-booking/blob/develop/src/perf-tests/Makefile) is missing the deploy method.

**Fix:**
- Change `deploy.perftest` to `deploy` in the src/perf-tests/Makefile
- Change `delete.perftest` to `delete` in the src/perf-tests/Makefile

**Comment by heitorlessa** [comment]
Thanks Pawan! Just merged
