### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by jgroom33** [aws-samples/aws-serverless-airline-booking#141]
Thanks for creating this example app.

It would be helpful if this app used the default amplify app structure.

```
src # front-end
amplify
  backend
    function
      ConfirmBooking
      .....
    stepfunction
    auth
```

**Comment by heitorlessa** [comment]
Hi Jeff - Great to hear you found it helpful.

The default structure, and the features you highlight in that structure aren't sufficient for this project, hence why we don't use Amplify-CLI that way.

I'm completing the last Amplify JS and Web components, and Quasar (UI framework) breaking changes by end of Feb and merge them back here in develop -- once merger, I'll start looking at migrating from Amplify-CLI into either full SAM templates or CDK.

I'll add these decisions with their rationale in the decision log file.

Thank you!

**Comment by jgroom33** [comment]
Thanks @heitorlessa

I greatly appreciate projects that demonstrate a complex use case in a recommended framework.

I'm looking forward to the output of what you determine.
