### ISSUE TITLE
Frontend: Refactor to upgrade to now stable Quasar v2/Vue 3

### ISSUE THREAD

**Issue by heitorlessa** [aws-samples/aws-serverless-airline-booking#158]
Vue 3 makes it easier to use composition and will ease testing, documentation, and possibly simplify current state management.

Guide to migrate from Quasar v1 to v2: https://quasar.dev/start/upgrade-guide#migrate-to-v2-from-v1

**Comment by sthulb** [comment]
Thank you for creating this issue.

The issue is being closed because the project will no longer use Vue/Quasar. It will migrate to another framework in the future.
