### ISSUE TITLE
[Payment] New API

### ISSUE THREAD

**Issue by heitorlessa** [aws-samples/aws-serverless-airline-booking#171]
Payment today is largely a [thin abstraction to Stripe](https://github.com/aws-samples/aws-serverless-airline-booking/blob/develop/src/backend/payment/template.yaml#L30), as we wanted to demonstrate how customers could use SAR for app composition. As the Airline evolved, payment SAR App didn't. 

We can fix this and other related issues like latency, disjoint endpoints, and AuthZ, by creating the API end-to-end, yet talking to Stripe directly instead of through the SAR App.

Minimal changes:

* [ ] Recreate [Stripe SAR App API](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:375983427419:applications~api-lambda-stripe-charge) - payment authorization, payment collection, payment refund
* [ ] Ensure idempotency as Stripe does
* [ ] Integrate GraphQL API with new Payment API directly via HTTP Data Sources
* [ ] Update Process Booking State Machine to use Payment API not cross-function invoke
* [ ] Tests

Optional depending who's tackling the issue:

* [ ] Use Ports & Adapters to more easily change Payment gateway
  * [ ] Front-end might not be easily swappable due to iFrame security protections & card elements

**Comment by ArpanShah2k** [comment]
I am interested in fixing this issue. it will be great opportunity to solve it, if you allot me this issue . @heitorlessa @sthulb @julienlepine @hyandell @deldrid1
