### ISSUE TITLE
Error when deploying: API key must be valid for a minimum of 1 days

### ISSUE THREAD

**Issue by heitorlessa** [aws-samples/aws-serverless-airline-booking#186]
**Problem**

New deployments are failing due to an old API key setting that Amplify Console doesn't seem to be picking up. This issue tracks the resolution and potentially reverting dual-authorization setting.

```bash
2022-03-22T09:06:31.717Z [INFO]: DELETE_COMPLETE          authawsserverlessairline44ea6421        AWS::CloudFormation::Stack Tue Mar 22 2022 09:06:30 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_ROLLBACK_COMPLETE amplify-awsserverlessairline-devf-85837 AWS::CloudFormation::Stack Tue Mar 22 2022 09:06:31 GMT+0000 (Coordinated Universal Time)
2022-03-22T09:06:47.249Z [INFO]: Following resources failed
                                 Resource Name: GraphQLAPIKey (AWS::AppSync::ApiKey)
                                 Event Type: create
                                 Reason: API key must be valid for a minimum of 1 days. (Service: AWSAppSync; Status Code: 400; Error Code: ApiKeyValidityOutOfBoundsException; Request ID: 1d752afe-7c47-42fe-b4e3-fcfed28f51a1; Proxy: null)
2022-03-22T09:06:47.251Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
                                    ✖ There was an error initializing your environment.
```

**Comment by heitorlessa** [comment]
Root cause: https://github.com/aws-amplify/amplify-cli/issues/4460

Next. Upgrade Amplify-CLI, reconfigure Auth (remove, re-add API Key). Failing that, set API Key to 2 days. Failing that somehow, then use CDK extension

**Comment by heitorlessa** [comment]
Amplify-CLI upgraded to 6.4.0 - last release before major breaking changes in GraphQL and in AuthZ model. It's deploying successfully now. However, I'll wait until tomorrow to confirm whether the new `apiKeyExpirationDate` field added doesn't impact deploys in future dates - If so, we'll have to replace API Key with AWS_IAM AuthZ option for v2 e2e tests.

https://github.com/aws-samples/aws-serverless-airline-booking/commit/ff11056320934c268eba9fa13ca636cc055c0063

**Comment by sthulb** [comment]
Thank you for creating this issue.

The issue is being closed because the project will no longer use Amplify
