### ISSUE TITLE
ImportError: cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by jensenzelaya** [aws-samples/aws-serverless-airline-booking#193]
Jinja has removed functions in a recent version, and build is failing:

```
2022-04-02T20:25:17.271Z [INFO]: make[2]: Entering directory `/codebuild/output/src876565892/src/aws-serverless-airline-booking/src/backend/shared/libs'
.
.
File "/root/.local/lib/python3.7/site-packages/flask/__init__.py", line 14, in <module>
 from jinja2 import escape
 ImportError: cannot import name 'escape' from 'jinja2' (/root/.local/lib/python3.7/site-packages/jinja2/__init__.py)
2022-04-02T20:25:17.271Z [WARNING]: make[2]: *** [deploy] Error 1
2022-04-02T20:25:17.271Z [WARNING]: make[1]: *** [deploy.shared-lambda-layers] Error 2
 make: *** [deploy] Error 2
2022-04-02T20:25:17.271Z [INFO]: make[2]: Leaving directory `/codebuild/output/src632089102/src/aws-serverless-airline-booking/src/backend/shared/libs'
make[1]: Leaving directory `/codebuild/output/src632089102/src/aws-serverless-airline-booking'
2022-04-02T20:25:17.272Z [ERROR]: !!! Build failed
2022-04-02T20:25:17.272Z [ERROR]: !!! Non-Zero Exit Code detected
2022-04-02T20:25:17.272Z [INFO]: # Starting environment caching...
2022-04-02T20:25:17.273Z [INFO]: # Environment caching completed
```

According to Jinja documentation this should now be imported from `MarkupSafe` : [Version 3.1.0](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0)

As this comes from `/root/.local/lib/python3.7/site-packages/flask/__init__.py`, is `requirements.txt` the best way to fix it?

**Comment by jensenzelaya** [comment]
I modified `aws-serverless-airline-booking/src/backend/shared/libs/src/requirements.txt ` and added:
```
Jinja2==3.1.1
Flask==2.0.3
```

the build completes successfully. Would this be the best fix?

**Comment by heitorlessa** [comment]
Hi @jensenzelaya thanks for raising this issue. As this project pins dependencies I believe this is solving an issue elsewhere - could you share a full build log to find out where this issue is happening earlier?

This looks like an issue with SAM CLI as they use Flask for `sam local start-api`: https://github.com/aws/aws-sam-cli/issues/3791

If that's the case (logs would be great), the best solution here would be to [stop relying on aws-sam-cli package](https://github.com/aws-samples/aws-serverless-airline-booking/blob/develop/Makefile#L84) and use their [self-contained installers](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html#x86_64-) if they can't pin those dependencies.

I'm gonna try block 2 hours this Friday to look into it. If we were to pin `Jinja2` and `Flask` this would eventually become a problem with any other dependency we might use in the future (or if SAM CLI pins it)

**Comment by jensenzelaya** [comment]
Hi @heitorlessa sure, attached is the full failed build
[log.txt](https://github.com/aws-samples/aws-serverless-airline-booking/files/8455261/log.txt)

**Comment by hitchiceburg** [comment]
Is this relevant:

2022-05-01T15:05:57.843Z [WARNING]: ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
                                    We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
                                    serverlessrepo 0.1.10 requires pyyaml~=5.1, but you'll have pyyaml 6.0 which is incompatible.
                                    flask 1.1.4 requires Jinja2<3.0,>=2.10.1, but you'll have jinja2 3.1.2 which is incompatible.
                                    aws-sam-cli 1.47.0 requires PyYAML~=5.3, but you'll have pyyaml 6.0 which is incompatible.

should we restrict the versions of pyyaml, Jinja2

**Comment by heitorlessa** [comment]
Hi Mike - both of them are used by SAM CLI, which we install using pip at
CI. What we need to do is change CI (make dev) to download a Linux
self-contained installer.

I’m estimating to get this and another issue[1] done in two to three weeks
from now.

[1] Amplify Console 1-click deployment recently changed for new customers.
Amplify team scopes down permissions of new IAM Roles which are now
incompatible with what we need. We will need to change our deployment
process, and document IAM permissions we will need beyond CloudFormation.

**Comment by hitchiceburg** [comment]
Thanks Heitor - Can you point me in the right direction? Maybe I can change the CI to try this self-contained installer and test it out? 

Is this what you mean?
curl -O https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
sudo ./sam-installation/install --update

**Comment by heitorlessa** [comment]
That’s exactly it, Mike. For CI, it’s on line 84

https://github.com/aws-samples/aws-serverless-airline-booking/blob/develop/Makefile
