### ISSUE TITLE
Error in building project to Amplify Console

### ISSUE THREAD

**Issue by Arc-dev** [aws-samples/aws-serverless-airline-booking#32]
Hey folks,

I just tied to build this into my Amplify Console account and ran into a build error. Looks like it's related to this GitHub issue[1] with the newest version of the CLI. 

I've edited my forked repo and tried pushing back the version to 1.10.0/1.9.0 as well as adding the unsafe-perm as below,

`npm -g install @aws-amplify/cli --unsafe-perm=true`

Both of these seem to not fix the issue due to other dependencies.

Cheers!
Ref
[1]. https://github.com/aws-amplify/amplify-cli/issues/1996

**Comment by Arc-dev** [comment]
Turns out I'm just an idiot!

I attempted to deploy this twice and it turns out it was crashing due to a Stripe role that was created the first time. I removed all my stacks and rebuilt using the yml build file with the --unsafe-perm true tag.
`npm install -g @aws-amplify/cli --unsafe-perm=true # install latest amplify-CLI`

This pushed me past the DynamoDb mock dependency so I'll fork the repo and add this change into the yml file for now.

**Comment by heitorlessa** [comment]
hey @Arc-dev,

 Thanks for reporting that - I'll pin Amplify CLI version in `amplify.yml` file. 

 Ideally you wouldn't need to pass `--unsafe-perm` - I'll create an issue for that and link this up and pin to the last known working version

**Comment by heitorlessa** [comment]
Also noticed today that the latest CLI introduced IdentityPoolId resource where it fails in new deployments for Console - Fixing all of that in an upcoming commit
