### ISSUE TITLE
Is this meant to be secure?

### ISSUE THREAD

**Issue by RossWilliams** [aws-samples/aws-serverless-airline-booking#34]
I see you are using @auth directives and stating this is a complete solution. Is the intention for this sample project to be protecting Booking models from public access? Are you aware that a person can open a websocket connection to IoT and see a stream of created bookings? Also, your architecture diagram is missing IoT.

**Comment by heitorlessa** [comment]
Hi @RossWilliams thank you for opening an issue - This is not complete yet, there are WIP PRs, and READMEs for each folder/service haven't been pushed out yet. 

re: Subscription, yes I'm aware, and am currently waiting for this RFC to implement that: https://github.com/aws-amplify/amplify-cli/issues/1043

I've updated the README with a status and an ETA to call this complete

**Comment by RossWilliams** [comment]
you can also use @model(subscriptions: null) to turn off subscriptions, no need to wait for #1043.

**Comment by heitorlessa** [comment]
Great point, will do that as I'm not using Subscriptions at the moment anywhere in the front-end. 

Will leave this open so I can fix that right after merging the [Python observability lib](https://github.com/aws-samples/aws-serverless-airline-booking/pull/27).

Thanks again @RossWilliams
