### ISSUE TITLE
Please update the README

### ISSUE THREAD

**Issue by ha-king** [aws-samples/aws-serverless-airline-booking#4]
I will not be able to sleep properly until I deploy this entire application.  Please have sympathy for me and others like me whom desire to know how to deploy this fancy solution.

Oh, Captain, my captain...

**Comment by dancomanlive** [comment]
How about a Deploy to Amplify Console Button ?

**Comment by heitorlessa** [comment]
> How about a Deploy to Amplify Console Button ?
> Oh, Captain, my captain...

I was planning to update the README before Phase 2 as now it's mostly prototyping and a lot will change. 

If you are okay with a Deploy Button with where we are and not with all back-end services I'm happy to do that ;)

**Comment by heitorlessa** [comment]
I've added a 1-click deploy button for now, but I'm reserving next Friday to do a revamp on the docs to set expectations and some timelines. 

<p align="center">
    <a href="https://console.aws.amazon.com/amplify/home#/deploy?repo=https://github.com/aws-samples/aws-serverless-airline-booking">
        <img src="https://oneclick.amplifyapp.com/button.svg" alt="Deploy to Amplify Console">
    </a>
</p>

I've just created a separate issue to track efforts on updating README as there are few areas to complete based on feedback we've been receiving offline - https://github.com/aws-samples/aws-serverless-airline-booking/issues/9

Also added a [episode0](https://github.com/aws-samples/aws-serverless-airline-booking/tree/episode0) branch that contains bare bones Front-end (mocked data, and pending readme updates too). You can deploy `develop` in Amplify Console, and then connect this branch to have a Front-end you can hack around and evolve -- That will be the basis for the `unassisted workshop` by Mid/End-Aug.

Thanks again for opening this up - Hopefully the other issue provides more clarity on where we are heading
