### ISSUE TITLE
[Front-end] Vue testing

### ISSUE THREAD

**Issue by heitorlessa** [aws-samples/aws-serverless-airline-booking#44]
After [migration to Quasar 1.0](https://github.com/aws-samples/aws-serverless-airline-booking/issues/43) where `card` is a breaking change, we need to start writing Vue tests.

While E2E tests is done we need both unit testing for components and functional for the store.

Useful resource to start with: https://vue-test-utils.vuejs.org/

**Comment by sthulb** [comment]
Thank you for creating this issue.

The issue is being closed because the project will no longer use Vue/Quasar. It will migrate to another framework in the future.
