### ISSUE TITLE
Small nits

### ISSUE THREAD

**Issue by rhboyd** [aws-samples/aws-serverless-airline-booking#51]
https://github.com/aws-samples/aws-serverless-airline-booking/blob/develop/src/backend/booking/template.yaml#L263-L274

This is redundant, no?

https://github.com/aws-samples/aws-serverless-airline-booking/blob/develop/src/backend/booking/template.yaml#L126

I don't think this is needed since the SFN doesn't interact directly with the booking table.

**Comment by heitorlessa** [comment]
First one yes, second no. On mobile now, but have a look at the same file
under the Observability PR — Lots do fixes there including the first.

I’m merging that this coming Friday

**Comment by heitorlessa** [comment]
Actually, that's right on the second piece --- I had converted the Booking Table integration into Lambda Functions, so no need for that anymore.

Created issue https://github.com/aws-samples/aws-serverless-airline-booking/issues/53 so I can fix, right after merging PR https://github.com/aws-samples/aws-serverless-airline-booking/pull/27 that already contain fixes for 1 and the DLQ feature.

This is the latest State Machine with fixes until I complete the PR: https://github.com/aws-samples/aws-serverless-airline-booking/pull/27/files#diff-ea15fbc3afdd97e8464668af03f9d557R147
