### ISSUE TITLE
Add Gatling perf load test from bonus episode

### ISSUE THREAD

**Issue by heitorlessa** [aws-samples/aws-serverless-airline-booking#56]
Discussed with @pputhran about creating a PR to add load testing under `src`. 

A few implementation details to think before merging:

* [ ] Fake usernames for load testing
* [ ] Environment variables for URLs
* [ ] Share CloudFormation to launch EC2 as Gatling instances
* [ ] Allow load test to run from one's laptop (Docker)

**Comment by pputhran** [comment]
PR - https://github.com/aws-samples/aws-serverless-airline-booking/pull/81
