### ISSUE TITLE
Not getting any flight 

### ISSUE THREAD

**Issue by MThakkar121** [aws-samples/aws-serverless-airline-booking#78]
not getting any flights arrival departure details, after setting up the web application and running it ! it runs successfully but after the logging in didn't getting any flights..

**Comment by heitorlessa** [comment]
Have you followed the steps to manually add a flight? If so, can you try
adding a flight for November as I think there is a bug in the resolver?

It’d be great to hear what steps you’ve taken too

**Comment by MThakkar121** [comment]
I've followed all the steps which are explained in to the readme.md file !!

Wait, please explain me, I mean help me with that! how can I implement by following manual steps ?

**Comment by heitorlessa** [comment]
Hi Mayur,

 Please follow these manual steps to add your flights into the system and then you should be able to find them when searching in the web app - https://github.com/aws-samples/aws-serverless-airline-booking#adding-your-first-flight

 Notice the mutation **flight1** that adds a flight for **London Gatwick/Madrid** on **Dec 2nd** - https://github.com/aws-samples/aws-serverless-airline-booking/blob/develop/sample-queries-mutations.gql#L4

 If the instructions succeeded and you've got your first flight added in the DB, the following query should work for you - Similarly to the instructions, you can run them within AppSync Console:

```graphql
query {
  listFlights(limit:2){
    items {
      id,
      departureDate,
      departureAirportCode,
      departureAirportName,
      departureCity,
      departureLocale,
      arrivalDate,
      arrivalAirportCode,
      arrivalAirportName,
      arrivalCity,
      arrivalLocale,
      ticketPrice,
      ticketCurrency,
      flightNumber,
      seatAllocation,
      seatCapacity
    }
  }
}
```

Let me know the result of the query above once you have a chance.

Hope that helps and thanks for raising the issue

**Comment by MThakkar121** [comment]
Thank you for helping me out of these problem I'll tell you about the
results ASAP !

**Comment by heitorlessa** [comment]
Resolving this as of now, but please reopen once you've got the results to share :)
