### ISSUE TITLE
Upload video Episode 10 to 14

### ISSUE THREAD

**Issue by danketrotzdem** [aws-samples/aws-serverless-airline-booking#93]
Hi guys,
Happy new year! I am a big fan of this project. Thanks so much for the in-depth info. 
Could you also upload the videos to episode 10 and 14 on yt or twitch? 
This would be much appreciated. 

Thanks in advance,
Patrick

**Comment by miguelgimenez** [comment]
+1

**Comment by heitorlessa** [comment]
Hey @danketrotzdem and @miguelgimenez - Thanks a lot for the kind words :)

These are the direct links for the remaining episodes - We're working to update the landing page and include these:
 
* **Episode 10** - https://www.twitch.tv/videos/457858667
* **Episode 11** – https://www.twitch.tv/videos/457907686
* **Episode 12** – https://www.twitch.tv/videos/457923264
* **Episode 13** – https://www.twitch.tv/videos/471252879
* **Episode 14** - https://www.twitch.tv/videos/464384029

FYI, after I complete these activities I'll create a new branch named `twitch` so we can work on improving other areas: https://github.com/aws-samples/aws-serverless-airline-booking/projects/2

**Comment by miguelgimenez** [comment]
Muito obrigado Heitor!
Many thanks!!

**Comment by heitorlessa** [comment]
Finally came around to merge the last fixes and created the Twitch branch, including a list of all episodes along with their PRs

https://github.com/aws-samples/aws-serverless-airline-booking/tree/twitch#episodes
